#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os, sys
if __name__ == "__main__":
    args = sys.argv[1:]
    args_joined = " ".join(args)
    sys.exit(os.system(f"(proj_dir)/dependencies/noise_suppression/shell_files/noise_suppressor.sh {args_joined}"))
